version: '3.5'

services:
  postgres:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: datagrid-service
      POSTGRES_USER: cqdg
      POSTGRES_PASSWORD: password
    ports:
      - 5632:5432
  adminer:
    image: adminer
    ports:
      - 5280:8080
